location:
    source_directories:
        - /home/scrumplex
        - /media/DATA
        - /media/DATA2

    repositories:
        - obai58wh@obai58wh.repo.borgbase.com:repo

    exclude_patterns:
        - ~/.android
        - ~/.ccache
        - ~/.cargo
        - ~/.chroot
        - ~/.conan
        - ~/.gradle
        - ~/.local/share/baloo
        - ~/.local/share/containers
        - ~/.local/share/JetBrains
        - ~/.local/share/lutris/runners
        - ~/.local/share/lutris/runtime
        - ~/.local/share/PrismLauncher/assets
        - ~/.local/share/PrismLauncher/cache
        - ~/.local/share/PrismLauncher/libraries
        - ~/.local/share/PrismLauncher/meta
        - ~/.local/share/PrismLauncher/metacache
        - ~/.local/share/PrismLauncher/translations
        - ~/.local/share/Steam/appcache
        - ~/.local/share/Steam/compatibilitytools.d
        - ~/.local/share/Steam/config/htmlcache
        - ~/.local/share/Steam/depotcache
        - ~/.local/share/Steam/steamapps
        - ~/.local/share/Trash
        - ~/.local/share/virtualenv
        - ~/.local/share/virtualenvs
        - ~/.m2
        - ~/.node-gyp
        - ~/.npm
        - ~/.nvm
        - ~/.rbenv
        - ~/.rustup
        - ~/.steam
        - ~/.tmp
        - ~/.wine
        - ~/.yarn
        - ~/kde
        - ~/Lutris
        - /media/DATA/Games
        - /media/DATA/ItchLibrary
        - /media/DATA/Torrents
        - /media/DATA2/SteamLibrary
        - "*/.cache"
        - "*/.pnpm-store"
        - "*/.snapshots"
        - "*/.Trash-*"

    exclude_caches: true
    exclude_if_present:
        - .nobackup

storage:
    compression: zstd

retention:
    # Keep all archives within this time interval.
    # keep_within: 1M

    # Number of secondly archives to keep.
    # keep_secondly: 60

    # Number of minutely archives to keep.
    # keep_minutely: 60

    # Number of hourly archives to keep.
    # keep_hourly: 24

    # Number of daily archives to keep.
    keep_daily: 7

    # Number of weekly archives to keep.
    keep_weekly: 6

    # Number of monthly archives to keep.
    keep_monthly: 6

    # Number of yearly archives to keep.
    keep_yearly: 2

hooks:
    before_backup:
        - echo "Starting a backup."
        - systemd-notify --ready --status="Backing up..." || true
        - notify-send -a borgmatic "Automatic backup has been started" "Now running an automatic backup."

    before_prune:
        - echo "Starting pruning."
        - systemd-notify --ready --status="Pruning..." || true

    after_backup:
        - echo "Finished a backup."
        - systemd-notify --ready --status="Backup done" || true

    after_prune:
        - echo "Finished pruning."
        - systemd-notify --ready --status="Prune done" || true

    on_error:
        - echo "Error during prune/create."
        - systemd-notify --status="Failed" || true

