location:
    source_directories:
        - /home/scrumplex

    repositories:
        - h3v4oa43@h3v4oa43.repo.borgbase.com:repo

    exclude_patterns:
        - ~/.android
        - ~/.ccache
        - ~/.cargo
        - ~/.chroot
        - ~/.conan
        - ~/.gradle
        - ~/.local/share/baloo
        - ~/.local/share/containers
        - ~/.local/share/Jetbrains
        - ~/.local/share/lutris/runners
        - ~/.local/share/lutris/runtime
        - ~/.local/share/Steam/appcache
        - ~/.local/share/Steam/compatibilitytools.d
        - ~/.local/share/Steam/config/htmlcache
        - ~/.local/share/Steam/depotcache
        - ~/.local/share/Steam/steamapps
        - ~/.local/share/Trash
        - ~/.local/share/virtualenvs
        - ~/.m2
        - ~/.node-gyp
        - ~/.npm
        - ~/.nvm
        - ~/.rbenv
        - ~/.rustup
        - ~/.steam
        - ~/.tmp
        - ~/.wine
        - ~/.yarn
        - ~/kde
        - ~/Lutris
        - ~/Music      # already backed up by andromeda
        - ~/Nextcloud  # ditto
        - "*/.Trash-*"
        - "*/.cache"
        - "*/.snapshots"

    exclude_caches: true
    exclude_if_present:
        - .nobackup

storage:
    compression: zstd

retention:
    # Keep all archives within this time interval.
    # keep_within: 1M

    # Number of secondly archives to keep.
    # keep_secondly: 60

    # Number of minutely archives to keep.
    # keep_minutely: 60

    # Number of hourly archives to keep.
    # keep_hourly: 24

    # Number of daily archives to keep.
    keep_daily: 7

    # Number of weekly archives to keep.
    keep_weekly: 4

    # Number of monthly archives to keep.
    keep_monthly: 24

    # Number of yearly archives to keep.
    # keep_yearly: 1

hooks:
    before_backup:
        - echo "Starting a backup."
        - systemd-notify --ready --status="Backing up..."
        - notify-send -a borgmatic "Automatic backup has been started" "Now running an automatic backup."

    before_prune:
        - echo "Starting pruning."
        - systemd-notify --ready --status="Pruning..."

    after_backup:
        - echo "Finished a backup."
        - systemd-notify --ready --status="Backup done"

    after_prune:
        - echo "Finished pruning."
        - systemd-notify --ready --status="Prune done"

    on_error:
        - echo "Error during prune/create."
        - systemd-notify --status="Failed"

