abbr -ag -- g git
abbr -ag -- ga 'git add'
abbr -ag -- gap 'git add -p'
abbr -ag -- gca 'git commit -s --amend'
abbr -ag -- gcm 'git commit -sm'
abbr -ag -- gco 'git checkout'
abbr -ag -- gd 'git diff'
abbr -ag -- gdc 'git diff --cached'
abbr -ag -- gl 'git log'
abbr -ag -- gp 'git push'
abbr -ag -- gpl 'git pull'
abbr -ag -- gri 'git rebase --interactive'
abbr -ag -- grc 'git rebase --continue'
abbr -ag -- gs 'git status'
