{lib', ...}: {
  flake.nixosConfigurations = lib'.mkHost {
    hostName = "andromeda";
    modules = [
      ../common
      ../common/amdgpu
      ../common/bat.nix
      ../common/beets.nix
      ../common/bluetooth.nix
      ../common/boot
      ../common/desktop
      ../common/desktop/chromium.nix
      ../common/desktop/evolution.nix
      ../common/desktop/firefox.nix
      ../common/desktop/fuzzel.nix
      ../common/desktop/gaming.nix
      ../common/desktop/gtk
      ../common/desktop/image-viewer.nix
      ../common/desktop/inhibridge.nix
      ../common/desktop/keyring.nix
      ../common/desktop/kitty.nix
      ../common/desktop/mako.nix
      ../common/desktop/nicotine-plus.nix
      ../common/desktop/obs.nix
      ../common/desktop/pipewire
      ../common/desktop/polkit-agent.nix
      ../common/desktop/poweralertd.nix
      ../common/desktop/qt
      ../common/desktop/screenshot-bash.nix
      ../common/desktop/session-lock.nix
      ../common/desktop/sway.nix
      ../common/desktop/swayidle.nix
      ../common/desktop/vr.nix
      ../common/desktop/waybar.nix
      ../common/desktop/wlogout.nix
      ../common/desktop/wlsunset.nix
      ../common/desktop/wob.nix
      ../common/fish.nix
      ../common/flatpak.nix
      ../common/git.nix
      ../common/gpg.nix
      ../common/home.nix
      ../common/htop.nix
      ../common/libvirtd.nix
      ../common/misc.nix
      ../common/mpd.nix
      ../common/mpv.nix
      ../common/neovim.nix
      ../common/nix.nix
      ../common/nix-index.nix
      ../common/openssh.nix
      ../common/pkgs
      ../common/podman.nix
      ../common/printing.nix
      ../common/ranger.nix
      ../common/regional.nix
      ../common/remote-build-consumer.nix
      ../common/remote-build-provider.nix
      ../common/rtl-sdr.nix
      ../common/ssh.nix
      ../common/syncthing.nix
      ../common/tty.nix
      ../common/utils.nix
      ../common/v4l2loopback.nix
      ../common/wireshark.nix
      ../../home

      ./configuration.nix
    ];
  };
}
