directory: ~/Music
library: ~/Music/musiclibrary.db
clutter: Thumbs.DB .DS_Store .directory

import:
  move: yes
  timid: yes
  detail: yes
  bell: yes

ui:
  color: yes

plugins: absubmit acousticbrainz chroma duplicates edit fetchart mbcollection mbsync mpdstats mpdupdate replaygain scrub
include:
  - secrets.yaml

mpd:
  host: localhost
  port: 6600

replaygain:
  backend: gstreamer

