#!/bin/sh
#
# Based on https://git.sr.ht/~whynothugo/dotfiles/tree/adf6af990b0348974b657ed4241d4bcf83dbcea3/item/home/.local/lib/waybar-mic
#
# Original description:
#
# Helper for waybar to show current mic status.
#
# This shows a small icon with the current microphone status in the taskbar. I
# use a global hotkey (Super+M) to control the microphone, so I don't have to
# remember a different muting hotkey for each [web] application. It also makes
# it easier to make sure I'm muted when handling multiple things at once.
#
# Waybar's CSS is set so that an open mic is a RED icon, and it's less flashy
# when the mic is muted.
#
# It might make sense to hide the module if no microphone is unmuted. This
# depends on: https://github.com/Alexays/Waybar/issues/699

show() {
    muted=$(pamixer --default-source --get-mute 2> /dev/null)
    if [ "$muted" == "true" ]; then
        CLASS="muted"
        TEXT=""
    else
        CLASS="not-muted"
        TEXT=""
    fi

    jq --compact-output \
      --null-input \
      --arg text "$TEXT" \
      --arg class "$CLASS" \
      '{"text": $text, "class": $class}'
}

monitor() {
  show

  pactl subscribe | /usr/bin/grep --line-buffered "'change' on source" |
    while read -r _; do
      show
    done
  exit
}

monitor
