directory: ~/Music
library: ~/Music/musiclibrary.db
clutter: Thumbs.DB .DS_Store .directory

import:
  move: yes
  timid: yes
  detail: yes
  bell: yes

ui:
  color: yes

plugins: absubmit acousticbrainz alternatives chroma duplicates edit fetchart hook mbcollection mbsync mpdstats mpdupdate replaygain scrub
include:
  - secrets.yaml

alternatives:
  phone:
    directory: ../.Music.phone
    query: ""
    formats: mp3 opus aac

hook:
  hooks:
    - event: import
      command: beet alt update phone
    - event: import  # copy over cover art
      command: rsync -av --delete --include="*.png" --include="*.jpg" --include="*.jpeg" --include="*/" --include=".stfolder" --exclude="*" $HOME/Music/ $HOME/.Music.phone

mpd:
  host: localhost
  port: 6600

replaygain:
  backend: gstreamer

