directory: ~/Music
library: ~/Music/musiclibrary.db
clutter: Thumbs.DB .DS_Store .directory

import:
  move: yes
  timid: yes
  detail: yes
  bell: yes

ui:
  color: yes

plugins: alternatives chroma duplicates edit embedart fetchart hook mbcollection mbsync mpdstats mpdupdate replaygain scrub
include:
  - secrets.yaml

alternatives:
  phone:
    directory: ../.Music.phone
    query: ""
    formats: opus

mpd:
  host: localhost
  port: 6600

replaygain:
  backend: gstreamer

